-- Create PostgreSQL type aliases for H2 compatibility
CREATE DOMAIN IF NOT EXISTS CITEXT AS VARCHAR(255);
CREATE DOMAIN IF NOT EXISTS TIMESTAMPTZ AS TIMESTAMP WITH TIME ZONE;
CREATE DOMAIN IF NOT EXISTS INET AS VARCHAR(50);
CREATE DOMAIN IF NOT EXISTS BYTEA AS VARBINARY(10000);
