spring.datasource.url=jdbc:postgresql://localhost:5432/memorio
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# optional: see Flyway/JPA logs more clearly
logging.level.org.flywaydb=INFO
logging.level.org.hibernate.SQL=INFO

# --- JWT settings ---
security.jwt.secret=change-me-super-secret-at-least-32-bytes-long-123456
security.jwt.access-token-minutes=1
security.jwt.issuer=memorio-backend